### PR TITLE
Make Travis build APK

### PR DESCRIPTION
**Pull request by yjbanov**
/cc @lukef @alardizabal

### CODE REVIEW

**Comment by lukef** [comment]
Curious why you're building with API 23 vs 25?

**Comment by yjbanov** [comment]
Maybe I was doing something wrong, but I couldn't get 25 working on Travis. It may not be supported. Their docs don't even say they support 23: https://docs.travis-ci.com/user/languages/android/#Pre-installed-components

**Comment by lukef** [comment]
It was more a curiosity than anything. I think 23 is ok to get it up and running as there aren't any specific features > 23 we're targeting yet. 23 supports the new permissions system so it should be ok. Maybe we can add an issue to address the update later.

**Pull request merged**
