### PR TITLE
Fix compatibility problem with fluro@1.3.0 #62 fix

### PR DESCRIPTION
**Pull request by maksimr**

### CODE REVIEW

**Comment by Hixie** [comment]
@maksimr Sorry about the delay responding to this. Can you rebaseline your PR and resubmit it? I think we've fixed the problems with Travis/iOS so this should go green now.

**Comment by maksimr** [comment]
@Hixie sure, no problem! 

Done ✔️

**Comment by maksimr** [comment]
Ok, looks like it is already fixed

**Comment by Hixie** [comment]
Ah, great!

**Pull request closed without merging**
